### ISSUE TITLE
Cannot open port.

### ISSUE THREAD

**Issue by jrotaetxe** [emxsys/callattendant#144]
Hello.
I am having an slightly different problem wit an (also) Conexant modem.
First, I cannot really know where is the serial channel of the modem, and seems also the callattendant is having some kind of problem
I am with a Pi2 Model B and this is the log I can offer...venv) root@TELSPAMFILTER:/home/pi# callattendant
Command line options:
  --config=None
  --data-path=None
  --create-folder=False
[Configuration]
  BLOCKED_ACTIONS = ('greeting', 'record_message')
  BLOCKED_GREETING_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/blocked_greeting.wav
  BLOCKED_RINGS_BEFORE_ANSWER = 0
  BLOCK_ENABLED = True
  BLOCK_NAME_PATTERNS = {'V[0-9]{15}': 'Telemarketer Caller ID'}
  BLOCK_NUMBER_PATTERNS = {}
  BLOCK_SERVICE = NOMOROBO
  DATABASE = callattendant.db
  DATA_PATH = /root/.callattendant
  DB_FILE = /root/.callattendant/callattendant.db
  DEBUG = False
  ENV = production
  GPIO_LED_APPROVED_BRIGHTNESS = 100
  GPIO_LED_APPROVED_PIN = 15
  GPIO_LED_BLOCKED_BRIGHTNESS = 100
  GPIO_LED_BLOCKED_PIN = 17
  GPIO_LED_MESSAGE_BRIGHTNESS = 100
  GPIO_LED_MESSAGE_COUNT_KWARGS = {'active_high': True}
  GPIO_LED_MESSAGE_COUNT_PINS = (8, 7, 27, 23, 10, 11, 9, 18)
  GPIO_LED_MESSAGE_PIN = 4
  GPIO_LED_RING_BRIGHTNESS = 100
  GPIO_LED_RING_PIN = 14
  PERMITTED_ACTIONS = ()
  PERMITTED_GREETING_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/general_greeting.wav
  PERMITTED_RINGS_BEFORE_ANSWER = 4
  PERMIT_NAME_PATTERNS = {}
  PERMIT_NUMBER_PATTERNS = {}
  PHONE_DISPLAY_FORMAT = ###-###-####
  PHONE_DISPLAY_SEPARATOR = -
  ROOT_PATH = /home/pi/venv/lib/python3.7/site-packages/callattendant
  SCREENED_ACTIONS = ()
  SCREENED_GREETING_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/general_greeting.wav
  SCREENED_RINGS_BEFORE_ANSWER = 0
  SCREENING_MODE = ('whitelist', 'blacklist')
  TESTING = False
  VERSION = 1.1.0
  VOICE_MAIL_GOODBYE_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/goodbye.wav
  VOICE_MAIL_GREETING_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/general_greeting.wav
  VOICE_MAIL_INVALID_RESPONSE_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/invalid_response.wav
  VOICE_MAIL_LEAVE_MESSAGE_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/please_leave_message.wav
  VOICE_MAIL_MENU_FILE = /home/pi/venv/lib/python3.7/site-packages/callattendant/resources/voice_mail_menu.wav
  VOICE_MAIL_MESSAGE_FOLDER = /root/.callattendant/messages
Initializing Modem
Opening serial port
Looking for modem on /dev/ttyAMA0
Looking for modem on /dev/ttyprintk
Modem initialized
{MSG LED OFF}
Starting the Flask webapp
Running the Flask server
Waiting for call...
 * Serving Flask app "userinterface.webapp" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Exception in thread modem_call_handler:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/venv/lib/python3.7/site-packages/callattendant/hardware/modem.py", line 236, in _call_handler
    modem_data = self._serial.readline()
  File "/home/pi/venv/lib/python3.7/site-packages/serial/serialposix.py", line 560, in read
    raise PortNotOpenError()
serial.serialutil.PortNotOpenError: Attempting to use a port that is not open

^C** User initiated shutdown

Can any of you help me?

**Comment by jrotaetxe** [comment]
Not an issue...
Seems the modem is a softmodem Raspbian cannot install properly. Beware soft-modems to take this project
