### ISSUE TITLE
Front end fails to initialize due to call to missing table field.

### ISSUE THREAD

**Issue by zomGreg** [emxsys/callattendant#16]
Error:

```
Unhandled exception in thread started by <function flaskThread at 0x737973f0>
Traceback (most recent call last):
  File "/home/pi/testing/callattendant/src/userinterface/webapp.py", line 123, in flaskThread
    call_details()
  File "/home/pi/testing/callattendant/src/userinterface/webapp.py", line 62, in call_details
    result_set = screening.utils.query_db(get_db(), query, arguments)
  File "/home/pi/testing/callattendant/src/screening/utils.py", line 29, in query_db
    cur = db.execute(query, args)
sqlite3.OperationalError: no such column: b.Reason
```

Likely this is because the whitelist table contains no Reason field.

I will submit a PR with what I think is the fix.

**Comment by emxsys** [comment]
The problem is in whitelist.py.  The `Reason` field should follow the `Name` field:
```
class Whitelist(object):

    def __init__(self, db):
        """Ensures database access to the Whitelist table"""

        self.db = db

        sql = '''CREATE TABLE IF NOT EXISTS Whitelist (
            PhoneNo TEXT PRIMARY KEY,
            Name TEXT,
            SystemDateTime TEXT)'''
        curs = self.db.cursor()
        curs.executescript(sql)
        curs.close()
```
