### ISSUE TITLE
Virtual Env issues.

### ISSUE THREAD

**Issue by jumper-d-1981** [emxsys/callattendant#162]
I installed the virtualenv as described in the install walkthrough.  Once I did and set the other two commands, then attempted to download via pip, I get HTTP errors in orange text.  I restarted and tried again, same result.  Takes forever to complete the attempts and retries but never downloads.  Also after that the pi is running pihole super slow.  Any thoughts?

**Comment by jumper-d-1981** [comment]
well after a second restart it took the command and installed...found the modem...as soon as I dialed a test call, pihole died and then call attendent stopped working.  Since pihole died my network dns went down.

Is the two softwares running at the same time, one in virtual...too much for a pi 3b+, I checked systems resources when both were running and only 38% of RAM was used up...but there was plenty of CPU left.

I am confused.

**Comment by jumper-d-1981** [comment]
I am so stupid.  I am sorry to keep blowing you up.  I know that the slowness comes from accidentally installing it outside the virtual.  Now It gets almost done installing and not I get a bunch of red text siting an issue with GPIO

**Comment by jumper-d-1981** [comment]
Okay.  So I ran the cflags command mentioned in another user's issue.  It installed the gpio thing.  BUT now this is the output from running callattendent --createfolder

"Traceback (most recent call last):
  File "/home/pi/venv/bin/callattendant", line 8, in <module>
    sys.exit(main())
  File "/home/pi/venv/lib/python3.9/site-packages/callattendant/__main__.py", line 19, in main
    from app import main
  File "/home/pi/venv/lib/python3.9/site-packages/callattendant/app.py", line 35, in <module>
    from config import Config
  File "/home/pi/venv/lib/python3.9/site-packages/callattendant/config.py", line 15, in <module>
    from werkzeug.utils import import_string
  File "/home/pi/venv/lib/python3.9/site-packages/werkzeug/__init__.py", line 2, in <module>
    from .test import Client as Client
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 918, in get_code
  File "<frozen importlib._bootstrap_external>", line 587, in _compile_bytecode
ValueError: bad marshal data (invalid reference)
"

**Comment by jumper-d-1981** [comment]
GOT IT.  I think I was panicking.  I just uninstalled the virtualenv and call attendant then restarted and reinstalled from beginning after purge.  It worked this time...but I made sure to run an update...so I think I was running an out of date or problematic version of python.

Got it.  Thanks.
