### ISSUE TITLE
flask_paginate module not found when run as a service

### ISSUE THREAD

**Issue by emxsys** [emxsys/callattendant#42]
The following output from `sudo journalctl --follow -u callattendant.service shows the error:
```
Jul 31 01:14:28 pi-blocker systemd[1]: Started Call Attendant.
Jul 31 01:14:30 pi-blocker python[9919]: Traceback (most recent call last):
Jul 31 01:14:30 pi-blocker python[9919]:   File "/home/pi/callattendant/src/callattendant.py", line 32, in <module>
Jul 31 01:14:30 pi-blocker python[9919]:     import userinterface.webapp as webapp
Jul 31 01:14:30 pi-blocker python[9919]:   File "/home/pi/callattendant/src/userinterface/webapp.py", line 33, in <module>
Jul 31 01:14:30 pi-blocker python[9919]:     from flask_paginate import Pagination, get_page_args
Jul 31 01:14:30 pi-blocker python[9919]: ImportError: No module named flask_paginate
Jul 31 01:14:30 pi-blocker systemd[1]: callattendant.service: Main process exited, code=exited, status=1/FAILURE
Jul 31 01:14:30 pi-blocker systemd[1]: callattendant.service: Unit entered failed state.
Jul 31 01:14:30 pi-blocker systemd[1]: callattendant.service: Failed with result 'exit-code'.
```

callattendate.service Unit File:
```
[Unit]
Description=Call Attendant
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/python /home/pi/callattendant/src/callattendant.py
WorkingDirectory=/home/pi/callattendant/src
Restart=on-abort

[Install]
WantedBy=multi-user.target

```

*flask_paginate* was installed via the requirements.txt file. `pip show flask_paginate` shows the modules.

**Comment by emxsys** [comment]
The modules used by the service need to be installed for the root user, e.g.,

_For Python3 on the Raspberry Pi:_
```
cd [your path]/callattendant
sudo pip3 install -r requirements.txt
```
_else_
```
cd [your path]/callattendant
sudo pip install -r requirements.txt
```
The README should be updated to reflect this.
