### ISSUE TITLE
Error when adding a user to whitelist

### ISSUE THREAD

**Issue by zomGreg** [emxsys/callattendant#50]
192.168.1.106 - - [03/Aug/2020 17:44:39] "GET /manage_caller/3 HTTP/1.1" 200 -
Adding LNAME FNAME to whitelist
[2020-08-03 17:44:41,309] ERROR in app: Exception on /manage_caller/3 [POST]
Traceback (most recent call last):
  File "/home/pi/p3/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/p3/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/p3/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/p3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pi/p3/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/p3/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/projects/callattendant/src/userinterface/webapp.py", line 236, in manage_caller
    whitelist = Whitelist(get_db())

**Comment by zomGreg** [comment]
I'll take a look at this later. Just familiarizing myself with the new hotness. I ran into this issue when I clicked on a user and then attempted to add to the whitelist.

**Comment by zomGreg** [comment]
This happens on both whitelist and blacklist add attempts. I think the problem is that neither blacklist or whitelist actions have a knowledge of the config. I'm still reading and learning how this might work and be resolved. Please correct me if my assessment is wrong.
